const SEARCH_QUESTION = 'SEARCH_QUESTION';
const CLEAR_SEARCH = 'CLEAR_SEARCH';
const ADD_QUESTION = 'ADD_QUESTION';
const EDIT_QUESTION = 'EDIT_QUESTION';
const SORT_BY = 'SORT_BY';

export default {
    SEARCH_QUESTION,
    CLEAR_SEARCH,
    ADD_QUESTION,
    EDIT_QUESTION,
    SORT_BY
}